# Generated by Django 3.0.9 on 2021-05-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20210405_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetentry',
            name='category',
            field=models.CharField(choices=[('Rightwing', 'rightwing'), ('Leftwing', 'leftwing'), ('Defensemen', 'defensemen'), ('Center', 'center'), ('Goaltender', 'goaltender')], max_length=20),
        ),
    ]
