# Generated by Django 3.0.9 on 2021-05-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20210504_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetentry',
            old_name='description',
            new_name='player',
        ),
    ]
