# Generated by Django 3.0.9 on 2021-05-05 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20210504_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetentry',
            old_name='actual',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='budgetentry',
            old_name='category',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='budgetentry',
            old_name='projected',
            new_name='prediction',
        ),
    ]
