# Generated by Django 3.0.9 on 2021-05-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210329_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksentry',
            name='category',
            field=models.CharField(choices=[('Home', 'home'), ('School', 'school'), ('Work', 'work'), ('Self improvement', 'self improvement'), ('Other', 'other')], max_length=20),
        ),
    ]
