# Generated by Django 3.0.9 on 2021-05-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210504_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksentry',
            old_name='description',
            new_name='opposing',
        ),
        migrations.RemoveField(
            model_name='tasksentry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tasksentry',
            name='completed',
        ),
        migrations.AddField(
            model_name='tasksentry',
            name='win',
            field=models.CharField(choices=[('Win', 'win'), ('Loss', 'loss')], default='win', max_length=20),
        ),
    ]
